package jframe;
import java.awt.Frame;
import java.sql.*;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import static jframe.DBConnection.con;



public class Sign_up extends javax.swing.JFrame {

    /**
     * Creates new form Sign_up
     */
    public Sign_up() {
        initComponents();
    }

    public void insertuserdata(){
        String name = juser_name.getText();
        String psswd = jpassword.getText();
        String mail = jmail.getText();
        
        try{
            Connection con = DBConnection.getConnection();
            String sql = "insert into signup(name,password,email) values(?,?,?)";
            PreparedStatement pst = con.prepareStatement(sql);
            
            pst.setString(1, name);
            pst.setString(2, psswd);
            pst.setString(3, mail);
            
            int updateRowCount = pst.executeUpdate();
            
            if(updateRowCount > 0){
                JOptionPane.showMessageDialog(this,"Insertion successfull");
            }else{
                JOptionPane.showMessageDialog(this,"Insertion Failed");
            }
            
            
        }catch(Exception e){
           e.printStackTrace();
        }
         
    }
    
    public boolean Validate(){
        String name = juser_name.getText();
        String psswd = jpassword.getText();
        String mail = jmail.getText();
        
        if(name.equals("")){
            JOptionPane.showMessageDialog(this, "Enter Username!");
        }
        
        if(psswd.equals("")){
            JOptionPane.showMessageDialog(this, "Enter Password!");
        }
        
        if(mail.equals("") || !mail.matches("^.+@.+\\..+$")){
            JOptionPane.showMessageDialog(this, "Enter Email Address!");
        }
        
        return true;
    }
    
    public boolean checkDupUser(){
        String name = juser_name.getText();
        boolean isExist = false;
        
           try{
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/Imp_Gen2?autoReconnect=true&useSSL=false","root","Shubham18#");
            PreparedStatement pst = con.prepareStatement("select * from signup where name =?");
            
            pst.setString(1, name);
            ResultSet rs = pst.executeQuery();
            if(rs.next()){
                isExist = true;
            }else{
                isExist = false;
            }
            
        }catch (Exception e){
            e.printStackTrace();
        }
        
        
        return isExist;
    }
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jpassword = new app.bolivia.swing.JCTextField();
        jLabel7 = new javax.swing.JLabel();
        jmail = new app.bolivia.swing.JCTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        login = new rojerusan.RSMaterialButtonCircle();
        signup = new rojerusan.RSMaterialButtonCircle();
        juser_name = new app.bolivia.swing.JCTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jmin2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanel1MouseDragged(evt);
            }
        });
        jPanel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel1MousePressed(evt);
            }
        });
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons/signup-library-icon.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 150, 864, 591));

        jLabel2.setFont(new java.awt.Font("STZhongsong", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(252, 197, 192));
        jLabel2.setText("Generator");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 90, 326, 52));

        jLabel3.setFont(new java.awt.Font("STZhongsong", 1, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(198, 137, 198));
        jLabel3.setText("Important Topic ");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 40, 326, 52));

        jPanel2.setBackground(new java.awt.Color(147, 125, 194));
        jPanel2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jPanel2.setForeground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("STZhongsong", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(97, 12, 99));
        jLabel4.setText("Create a New Account");
        jLabel4.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 100, 165, 28));

        jLabel6.setFont(new java.awt.Font("Lucida Fax", 1, 18)); // NOI18N
        jLabel6.setText("UserName:");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 150, 111, 29));

        jpassword.setBackground(new java.awt.Color(147, 125, 194));
        jpassword.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        jpassword.setFont(new java.awt.Font("Dubai", 1, 14)); // NOI18N
        jpassword.setPlaceholder("Enter Password....");
        jpassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jpasswordActionPerformed(evt);
            }
        });
        jPanel2.add(jpassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 260, 219, -1));

        jLabel7.setFont(new java.awt.Font("Lucida Fax", 1, 18)); // NOI18N
        jLabel7.setText("Password:");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 230, 111, 29));

        jmail.setBackground(new java.awt.Color(147, 125, 194));
        jmail.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        jmail.setFont(new java.awt.Font("Dubai", 1, 14)); // NOI18N
        jmail.setPlaceholder("Enter Your Email Address....");
        jmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmailActionPerformed(evt);
            }
        });
        jPanel2.add(jmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 340, 219, -1));

        jLabel8.setFont(new java.awt.Font("Lucida Fax", 1, 18)); // NOI18N
        jLabel8.setText("E-mail:");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 310, 111, 29));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons/icons8_Secured_Letter_50px.png"))); // NOI18N
        jLabel9.setText("jLabel9");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 340, 50, 40));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons/icons8_Account_50px.png"))); // NOI18N
        jLabel10.setText("jLabel9");
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 170, 50, 50));

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons/icons8_Forgot_Password_50px_4.png"))); // NOI18N
        jLabel11.setText("jLabel9");
        jPanel2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 250, 50, 50));

        login.setBackground(new java.awt.Color(232, 160, 191));
        login.setText("Login");
        login.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                loginMouseClicked(evt);
            }
        });
        login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginActionPerformed(evt);
            }
        });
        jPanel2.add(login, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 470, 180, 60));

        signup.setBackground(new java.awt.Color(97, 12, 99));
        signup.setText("Sign-Up");
        signup.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                signupMouseClicked(evt);
            }
        });
        signup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signupActionPerformed(evt);
            }
        });
        jPanel2.add(signup, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 410, 180, 60));

        juser_name.setBackground(new java.awt.Color(147, 125, 194));
        juser_name.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        juser_name.setFont(new java.awt.Font("Dubai", 1, 14)); // NOI18N
        juser_name.setPlaceholder("Enter User Name....");
        juser_name.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                juser_nameFocusLost(evt);
            }
        });
        juser_name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                juser_nameActionPerformed(evt);
            }
        });
        jPanel2.add(juser_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 180, 219, -1));

        jLabel12.setFont(new java.awt.Font("STZhongsong", 1, 36)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(252, 197, 192));
        jLabel12.setText("Sign Up");
        jPanel2.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 50, 165, 52));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 80, 400, 620));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("X");
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel5MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(1370, 0, 20, 40));

        jmin2.setFont(new java.awt.Font("Tahoma", 0, 60)); // NOI18N
        jmin2.setForeground(new java.awt.Color(0, 0, 0));
        jmin2.setText("-");
        jmin2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jmin2MouseClicked(evt);
            }
        });
        jPanel1.add(jmin2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1330, 10, -1, 30));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1520, 830));

        setSize(new java.awt.Dimension(1405, 749));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jpasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jpasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jpasswordActionPerformed

    private void jmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jmailActionPerformed

    private void loginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_loginActionPerformed

    private void signupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signupActionPerformed
        // TODO add your handling code here:
        if(Validate()==true){
            if(checkDupUser()==false){
                insertuserdata();
            }else{
                JOptionPane.showMessageDialog(this, "User already exist!");
            }
        }
    }//GEN-LAST:event_signupActionPerformed

    private void juser_nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_juser_nameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_juser_nameActionPerformed

    private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseClicked
            System.exit(0);
    }//GEN-LAST:event_jLabel5MouseClicked
private int xMouse, yMouse;
    private void juser_nameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_juser_nameFocusLost
        if(checkDupUser() == true){
            JOptionPane.showMessageDialog(this, "username already exist");
        }
    }//GEN-LAST:event_juser_nameFocusLost

    private void loginMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginMouseClicked
           login lo = new login();
           lo.setVisible(true);
           this.dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_loginMouseClicked

    private void jPanel1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MousePressed
        // TODO add your handling code here:
         xMouse = evt.getX();
        yMouse = evt.getY();
    }//GEN-LAST:event_jPanel1MousePressed

    private void jPanel1MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MouseDragged
        // TODO add your handling code here:
           int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        setLocation(x-xMouse,y-yMouse);
    }//GEN-LAST:event_jPanel1MouseDragged

    private void jmin2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jmin2MouseClicked
        // TODO add your handling code here:
        setExtendedState(Frame.ICONIFIED);
    }//GEN-LAST:event_jmin2MouseClicked

    private void signupMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_signupMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_signupMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Sign_up.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Sign_up.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Sign_up.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Sign_up.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>


        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Sign_up().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private app.bolivia.swing.JCTextField jmail;
    private javax.swing.JLabel jmin2;
    private app.bolivia.swing.JCTextField jpassword;
    private app.bolivia.swing.JCTextField juser_name;
    private rojerusan.RSMaterialButtonCircle login;
    private rojerusan.RSMaterialButtonCircle signup;
    // End of variables declaration//GEN-END:variables
}
